powerdata <- read.table(pipe('grep "^[0-2]/2/2007" "household_power_consumption.txt"'),header=F,sep=';')
colnames(powerdata) <- names(read.table('household_power_consumption.txt', header=TRUE, sep=";", nrows=1))
png("plot2.png", width=480, height=480)
date_and_time <- paste(powerdata$Date, powerdata$Time)
newdatetime <- strptime(date_and_time,format="%d%m%Y %H:%M:%S")
with(powerdata$newdatetime, plot(powerdata$Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xaxt='n', ann=FALSE))
axis(side=1, at=c(0,1500,2880), labels=c('Thu', 'Fri', 'Sat'))
dev.off()